---
title: "Untitled"
author: "Nikolaj Pedersen"
date: "2024-01-26"
output: pdf_document
---

```{r}
library(stringr)
```


```{r}
AV <- read.csv("~/AU/Speciale/Envidan data/AV/pipes_63.csv")

AV$DandasID <- "AV"

AV$ID  <- paste(AV$ID,AV$DandasID, sep = "_")
AV$LedningID  <- paste(AV$LedningID,AV$DandasID, sep = "_")

NF <- read.csv("~/AU/Speciale/Envidan data/NF/pipes_17462.csv")

NF$DandasID <- "NF"

NF$ID  <- paste(NF$ID,NF$DandasID, sep = "_")
NF$LedningID  <- paste(NF$LedningID,NF$DandasID, sep = "_")

VC <- read.csv("~/AU/Speciale/Envidan data/VC/pipes_17466.csv")
VC <- VC[,colnames(NF)]

VC$DandasID <- "VC"

VC$ID  <- paste(VC$ID,VC$DandasID, sep = "_")
VC$LedningID  <- paste(VC$LedningID,VC$DandasID, sep = "_")

temp <- rbind(AV,NF,VC)[,-1]

Etableret_NA <- unique(temp$ID[which(temp$DatoEtableret_raw== "")])
nrow(temp)

AV <- read.csv("~/AU/Speciale/Envidan data/AV/pipes_tv63.csv")

AV$DandasID <- "AV"

AV$ID  <- paste(AV$ID,AV$DandasID, sep = "_")
AV$LedningID  <- paste(AV$LedningID,AV$DandasID, sep = "_")

NF <- read.csv("~/AU/Speciale/Envidan data/NF/pipes_tv17462.csv")

NF$DandasID <- "NF"

NF$ID  <- paste(NF$ID,NF$DandasID, sep = "_")
NF$LedningID  <- paste(NF$LedningID,NF$DandasID, sep = "_")

VC <- read.csv("~/AU/Speciale/Envidan data/VC/pipes_tv17466.csv")
VC <- VC[,colnames(NF)]

VC$DandasID <- "VC"

VC$ID  <- paste(VC$ID,VC$DandasID, sep = "_")
VC$LedningID  <- paste(VC$LedningID,VC$DandasID, sep = "_")

temp <- rbind(AV,NF,VC)[,-1]
nrow(temp)

#Fjerner observationer hvor Envidan har imputed etablerings dato
temp <- temp[which(!temp$ID %in% Etableret_NA),]

temp <- temp[which(!duplicated(temp[,c("ID","Obs")])),]

rm(AV,NF,VC)

#tilføj variable for inspiceret
temp$HasObs <- ifelse(temp$Obs == "", FALSE,TRUE)

temp$YearRapport <- as.numeric(stringr::str_sub(temp$DatoRapport,1,4))

temp$DateEtableret <- ifelse(is.na(temp$DatoEtableret_raw),NA, stringr::str_sub(temp$DatoEtableret_raw,1,10))
temp$DateEtableret <- as.Date(temp$DateEtableret)

temp$YearEtableret <- as.numeric(format(temp$DateEtableret, "%Y"))

temp$DateRapport <- ifelse(is.na(temp$DatoRapport),NA, stringr::str_sub(temp$DatoRapport,1,10))
temp$DateRapport <- as.Date(temp$DateRappor)

temp$YearRapport <- as.numeric(format(temp$DateRapport, "%Y"))

temp$DateSanering<- ifelse(is.na(temp$DatoSanering),NA, stringr::str_sub(temp$DatoSanering,1,10))
temp$DateSanering <- as.Date(temp$DateSanering)

temp$YearSanering <- as.numeric(format(temp$DateSanering, "%Y"))

temp <- temp[,which(!colnames(temp) %in% c("DatoSanering","DatoRapport","DatoEtableret_raw"))]

#Fjerner materialer som ikke er Plast eller Beton
temp<- temp[which(!(temp$MaterialeKode %in% c(0,8,9,12,13,14,15,16,17,27,50,61,64))),]

foo <- which(temp$MaterialeKode %in% c(6,7,18,19,21,24))
temp$Materiale[foo] <- "PE"

#reklassificerer materialer som plast eller Beton
temp$simplifiedMaterial <- as.factor(ifelse(temp$MaterialeKode == 1,"Beton",ifelse(temp$MaterialeKode == 5, "PVC", "Plast")))

#fjerner statuskode = 0,6,7 , i.e. ikke oplyst, projekterede eller anlagte ledninger
temp <- temp[which(!temp$StatusKode %in% c(6,7)),]

#fjerner fiktive ledninger
temp <- temp[which( temp$LednfunktionKode != 49),]

#kategoriserer saneringskode 0 som ikke saneret (fra NA for enkelte forsyninger)
temp$SaneringKode <- ifelse(is.na(temp$SaneringKode ),0,temp$SaneringKode)

#Kategoriser udskiftede saneringskode 1 som sanerede 
temp$Saneret <- ifelse(temp$SaneringKode == 1, 1, temp$Saneret)

#simplificer sankode til 0 ikke saneret, 1 udskiftet og 2 andet
foo <- which(temp$SaneringKode > 1)
temp$SaneringKode[foo] <- 2

#Antag ledninger med saneringsdato uden oplyst saneringskode er kategori 2
foo <- which(temp$SaneringKode == 0 & !is.na(temp$DateSanering))
temp$SaneringKode[foo] <- 2
temp$Saneret[foo] <- 1

#Hvis ledning er saneret (ikke udskiftet) ignorer statuskode
foo <- which( temp$StatusKode > 1 & temp$SaneringKode > 1)
temp$StatusKode[foo] <- 1

#Hvis ledning udskiftet og dateEtableret == dateSanering betragt som nyt
foo <- which(temp$DateEtableret == temp$DateSanering & temp$SaneringKode == 1)
temp$SaneringKode[foo] <- 0
temp$Saneret[foo] <- 0

#fjern ledninger med dateEtableret efter dateSaneret
foo <- which(temp$YearEtableret>  temp$YearSanering)
temp <- temp[-foo,]

#Ledninger uden saneringsdato men markeret som saneret fjernes
foo <- which(is.na(temp$YearSanering) & temp$SaneringKode > 0)
temp <- temp[-foo,]

#fjern ledninger etableret mere end 100 år siden
foo <- which(temp$YearEtableret <=1923)
temp <- temp[-foo,]

foo <- which(duplicated(temp[,c("ID")]))
temp$dup <- temp$LedningID %in% unique(temp$LedningID[foo])
nrow(temp)

temp$TypeAfloebKode <- as.factor(c("Sewage","Rain","Combined")[temp$TypeAfloebKode])
```

```{r}
Kat <- c("VA","RB","OB","PF","DE","FS","IS","RØ","IN","AF","BE","FO","GR","SG","PH","PB","OS","OP","OK")


obs <- c()
for(i in 0:4){
  obs <- c(obs,paste(Kat,i,sep = ""))
}

for(i in which(temp$Obs != "")){
  obs <- unique(c(obs,as.vector(strsplit(stringr::str_sub(temp$Obs[i], 2,-2),", ")[[1]])))
}
obs <- sort(obs)


Obs <- as.data.frame(matrix(0, ncol = length(obs), nrow = nrow(temp)))
colnames(Obs) <- obs

for(i in which(temp$Obs != "")){
  X <- table(as.vector(strsplit(stringr::str_sub(temp$Obs[i], 2,-2),", ")[[1]]))
  Obs[i,names(X)] <- X
}
Obs <- Obs[,which(nchar(colnames(Obs)) >2 )]

Obs[which(temp$Obs == ""), ] <- NA


obs <- colnames(Obs)

Comb <- cbind(stringr::str_sub(obs,1,2) == "VA" & str_extract(obs, "\\d+") == 0,
  stringr::str_sub(obs,1,2) == "VA" & str_extract(obs, "\\d+") %in% c("1","5","10","15","20"),
  stringr::str_sub(obs,1,2) == "VA" & str_extract(obs, "\\d+") %in% c("2","25","30","35","40"),
  stringr::str_sub(obs,1,2) == "VA" & str_extract(obs, "\\d+") %in% c("3","45","50","55","60"),
  stringr::str_sub(obs,1,2) == "VA" & str_extract(obs, "\\d+") %in% c("4","65","70","75","80","85","90","95","100"))

# for(j in c("RB","OB")){
#   for(i in 0:4){
#     Comb <- cbind(Comb, stringr::str_sub(obs,1,3) == paste(j,i,sep=""))
#   }
# }
# 
# # We let those who are not A,H,M,R be the first category, i.e. the severe group
# for(i in 0:4){
#   Comb <- cbind(Comb, stringr::str_sub(obs,1,3) == paste("PF",i,sep="") & !(stringr::str_sub(obs, 4,4) %in% c("A","H","M","R")))
# }
# for(i in 0:4){
#   Comb <- cbind(Comb, stringr::str_sub(obs,1,3) == paste("PF",i,sep="") & (stringr::str_sub(obs, 4,4) %in% c("A","H","M","R")))
# }

for(j in c("RB","OB","PF","DE","FS","IS","RØ","IN","AF","BE","FO","GR","SG","PH","PB","OS","OP","OK")){
  for(i in 0:4){
    Comb <- cbind(Comb, stringr::str_sub(obs,1,3) == paste(j,i,sep=""))
  }
}

Units <-  as.matrix(Obs)%*%(Comb + 0)
rm(Comb)


obs <- c()
for(j in 1:length(Kat)){
  for(i in 0:4){
    obs <- c(obs,paste(Kat[j],i,sep = ""))
  }
}
colnames(Units) <- obs

Units <- Units[,-which(stringr::str_sub(colnames(Units),3,3) == 0 & !(stringr::str_sub(colnames(Units),1,2) %in% c("VA","GR","OK")) )]

full <- cbind(temp,Units)

rm(temp)

full$condition <- full$DysfuncCode ==4 #rowSums(full[,c("RB4","FS4")]) >0

full$Age <- 2024 - full$YearEtableret

full$AgeFI <- full$YearRapport - ifelse(is.na(full$YearSanering)| full$DateRapport < full$DateSanering,full$YearEtableret,pmax(full$YearEtableret,full$YearSanering))

full[,c("CL","CL_B")] <- 0
full[,c("CR","CR_B")] <- Inf

full <- full[order(full$DandasID,full$ID,full$DateRappor),]
full$Case <- NA
```

```{r}
index <- 1:nrow(full)

#ignorer observationer uden inspektion eller sanering

foo <- which(!full$dup & !full$HasObs & !full$Saneret)
index <- setdiff(index,foo)

#ignorer observationer inspiceret med dateRapport == dateSanering
foo <- which(!full$dup & full$DateRapport == full$DateSanering)
index <- setdiff(index,foo)

#ignorer observationer inspiceret med dateEtableret == dateSanering
foo <- which(!full$dup & full$DateEtableret == full$DateSanering)
index <- setdiff(index,foo)

#ignorer observationer med unik inspektion før YearEtableret og YearLaid

#model A observationer: originale ledninger der er inspiceret. type II interval censureret
#                    - desuden antages udskiftede ledninger at have haft event
#model B observationer: antager sanering (kategori == 1) og ikke i brug har haft event  

#variable CL, CR venstre/højre censurering for model A, CL_B,CR_B venstre/højre censurering for model B,
#variabel ModelA: angiver om observation opfylder strenge krav af model A - boolean 

#type A: observationer med unik ID, ikke saneret, inspiceret, i brug
foo <- which(!full$dup & !full$Saneret & full$HasObs )
index <- setdiff(index, foo)
foo <- full[foo,]
foo[,c("CL","CL_B")] <- ifelse( foo$condition,0,foo$AgeFI)
foo[,c("CR","CR_B")] <- ifelse(foo$condition,foo$AgeFI+1, Inf)
foo$Case <- 1

#ignorer observationer som har negativ inspektion til tid 0
foo <- foo[-which(foo$CL ==0 & foo$CR == Inf),]

dat <- foo

#observationer unik ID, inspiceret inden sanering, 
#type A: hvis ikke-event højre censureret til uendelig, type B:hvis ikke-event højre censureret til sanering
#ignorerer Statuskode, da ikke bruger tilstand efter sanering.
foo <- which(!full$dup & (full$DateRapport < full$DateSanering))
foo <- intersect(foo,index)
index <- setdiff(index, foo)
foo <- full[foo,]
foo$AgeFI <- foo$YearRapport - foo$YearEtableret
foo[,c("CL","CL_B")] <- ifelse( foo$condition,0,foo$AgeFI)
foo$CR <- ifelse(foo$condition,foo$AgeFI+1, Inf)
foo$CR_B <- ifelse(foo$condition,foo$AgeFI+1, foo$YearSanering - foo$YearEtableret+1 )
foo$Case <- 2

dat <- rbind(dat,foo)

#observationer unik ID, saneret uden inspektion inden sanering(type B)
foo <- which(!full$dup & (full$DateRapport > full$DateSanering))
foo <- intersect(foo,index)
index <- setdiff(index, foo)
foo <- full[foo,]
foo$CL_B <- 0
foo$CR_B <- foo$YearSanering - foo$YearEtableret+1
foo$Case <- 3

dat <- rbind(dat,foo)

foo <- which(!full$dup & (!full$HasObs & full$Saneret))
foo <- intersect(foo,index)
index <- setdiff(index, foo)
foo <- full[foo,]
foo$CL_B <- 0
foo$CR_B <- foo$YearSanering - foo$YearEtableret+1
foo$Case <- 3

dat <- rbind(dat,foo)

#observation udskiftet med ekstra information
dat_temp <- dat[1,]
dat_temp <- dat_temp[-1,]

foo <- foo1 <- intersect(which(!full$dup & full$SaneringKode == 1),index)
for(i in foo){
  X <- full[i,]
  if(X$DateEtableret > X$DateSanering){
    if(X$DateRapport > X$DateSanering){
      X[,c("CL","CL_B")] <- ifelse(X$condition,0,X$AgeFI)
      X[,c("CR","CR_B")] <- ifelse(X$condition,X$AgeFI+1,Inf)
      foo1 <- setdiff(foo1,i)
      X$Case <- 6
      
      index <- setdiff(index,i)
      dat_temp <- rbind(dat_temp,X)
    }
  }else if(X$DateEtableret < X$DateSanering){
    if(X$DateRapport <= X$DateSanering){
      X[,c("CL","CL_B")] <- ifelse(X$condition,0,X$YearRapport- X$YearEtableret)
      X[,c("CR","CR_B")] <- ifelse(X$condition,X$YearRapport- X$YearEtableret+1,Inf)
      foo1 <- setdiff(foo1,i)
      X$Case <- 7
      
      index <- setdiff(index,i)
      dat_temp <- rbind(dat_temp,X)
    }else if(X$DateRapport > X$DateSanering){
      X$Case <- 8
      X[,c("CL","CL_B")] <- 0
      X[,c("CR","CR_B")] <- X$YearSanering - X$YearEtableret+1
      dat_temp <- rbind(dat_temp,X)
      
      X[,c("CL","CL_B")] <- ifelse(X$condition,0,X$AgeFI)
      X[,c("CR","CR_B")] <- ifelse(X$condition,X$AgeFI+1,Inf)
      
      index <- setdiff(index,i)
      foo1 <- setdiff(foo1,i)
      dat_temp <- rbind(dat_temp,X)
    }
  }else{
      X$Case <- 9
      X[,c("CL","CL_B")] <- ifelse(X$condition,0,X$AgeFI)
      X[,c("CR","CR_B")] <- ifelse(X$condition,X$AgeFI+1,Inf)
      
      index <- setdiff(index,i)
      foo1 <- setdiff(foo1,i)
      dat_temp <- rbind(dat_temp,X)
    }
}

dat <- rbind(dat,dat_temp)

dat_temp <- dat[1,]
dat_temp <- dat_temp[-1,]


foo <- foo1 <- unique(full$ID[which(full$dup)])

for(i in foo){
  j <- which(full$ID == i)
  X <- full[j,]
  Y <- X[,c("YearEtableret","YearSanering","SaneringKode","Saneret","StatusKode","HasObs")]
  n <- nrow(Y)
  if(sum(duplicated(Y)) == n-1){
    if( all(!X$Saneret & X$HasObs)){
      if(all(X$condition == 0)){
        X$Case <- 10
        X[,c("CL","CL_B")] <- max(X$AgeFI)
        
        X[,c("CR","CR_B")] <- Inf
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
        
      }else if(all(X$condition == 1)){
        X$Case <- 11
        X[1,c("CR","CR_B")] <-  min(X$AgeFI) +1
        X[1,c("CL","CL_B")] <- 0
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
      }else if(all(X$condition == cummax(X$condition))){
        X$Case <- 12
        X[1,c("CL","CL_B")] <- X$AgeFI[which.max(X$condition)-1]
        X[1,c("CR","CR_B")] <- X$AgeFI[which.max(X$condition)]+1
        X[1,"condition"] <- 1
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
      }else if(n == 2){
        X$Case <- 13
        X[1,c("CL","CL_B")] <- 0
        X[1,c("CR","CR_B")] <- X$AgeFI[1]+1
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
      }else if(all(X$DateRapport == X$DateRapport[1])){
        X$Case <- 14
        X[1,c("CL","CL_B")] <- 0
        X[1,c("CR","CR_B")] <- X$AgeFI[1]+1
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
      }else{
        X$Case <- 15
        Y <- X$condition
        if(Y[1] == 1){
          X[1,c("CL","CL_B")] <- 0
          X[1,c("CR","CR_B")] <- X$YearRapport[1] - X$YearEtableret[1] +1
        }else{
          X <- X[1:which.max(Y),]
          
          X[1,c("CL","CL_B")] <- X$AgeFI[which.max(X$condition)-1]
        X[1,c("CR","CR_B")] <- X$AgeFI[which.max(X$condition)]+1
        }
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
      }
    }else if( all(X$Saneret & X$HasObs & X$StatusKode == 1)){
      if(all(X$condition == 0) & all(X$DateRapport <= X$DateSanering)){
        X$Case <- 16
        X[1,c("CL","CL_B")] <- max(X$YearRapport - X$YearEtableret)
        X$CR <- Inf
        X$CR_B <- X$YearSanering[1]-X$YearEtableret[1]+1
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
        
      }else if(all(X$DateRapport > X$DateSanering)){
        X$Case <- 17
        X$CL_B <- 0
        X$CR_B <- X$YearSanering[1]-X$YearEtableret[1]+1
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
      }else if(all(X$YearRapport == X$YearSanering)){
        X$Case <- 18
        X[1,c("CL","CL_B")] <- 0
        X[1,c("CR","CR_B")] <- X$YearSanering[1]-X$YearEtableret[1]+1
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
      }else if(any(X$DateRapport[which(X$condition)] <= X$DateSanering[1])){
        X$Case <- 19
        X[1,c("CL","CL_B")] <- 0
        X[1,c("CR","CR_B")] <- min(X$YearRapport[which(X$condition & X$YearRapport <= X$YearSanering)])-X$YearEtableret[1]+1
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
      }else if(all(!X$condition[which(X$DateRapport <= X$DateSanering)])){
        X$Case <- 20
        X[1,c("CL","CL_B")] <- max(X$YearRapport[which(!X$condition & X$DateRapport <= X$DateSanering)])- X$YearEtableret[1]
        X$CR <- Inf
        X$CR_B <- c(X$YearSanering- X$YearEtableret)[1]+1
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
      }
    }else if(all(X$StatusKode > 1) ){
      if(all(!X$Saneret & !X$HasObs)){
        X$CL_B <- 0
        XCR_B <- c(2024- X$YearEtableret)[1]+1
        X$Case <- 21
        
        index <- setdiff(index,j)
        foo1 <- setdiff(foo1,i)
        dat_temp <- rbind(dat_temp,X[1,])
        
      }
    }
  }
}

dat <- rbind(dat,dat_temp)

dat$Type <- ifelse(dat$CR == dat$CR_B,"A",ifelse(dat$CL==0,"B","AB"))

foo <- which(dat$CL != 0)
dat$AgeFI[foo] <- dat$CL[foo]
foo <- which(dat$CR != Inf)
dat$AgeFI[foo] <- dat$CR[foo]

#type interval A
datA <- dat[-which(dat$CL==0 & dat$CR == Inf ),]

#type interval B
datB <- dat[-which(dat$CL_B==0 & dat$CR_B == Inf ),]

write.csv(dat,"~/AU/Speciale/DATA_NEW.csv")
```

```{r}
if(length(index) > 0){
View(full[index,c("ID","DateEtableret","DateRapport","DateSanering","StatusKode","SaneringKode","condition","dup","Obs")])
}
```


